name: Update Docker Hub Description

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  description:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME_VP }}
        password:  ${{ secrets.DOCKERHUB_TOKEN_VP }}
        repository: vponomarovatscylladb/hydra-loaders
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
